### ISSUE TITLE
Switching TV channels

### ISSUE THREAD

**Issue by Maks1776** [oxan/home-assistant-lg_netcast#2]
When integration is configured, the media player does not switch channels. One of the forums says that this may be due to the fact that the channels in tcm are written in Cyrillic. The integration is configured, for example, the volume is adjusted via HA and the TV can be turned off. Tell me how to set up channel switching.

**Comment by oxan** [comment]
I don't procure linear television, so I'm not able to test this, but I wouldn't expect the changes here to break this. Does it work correctly with the official HA integration?

**Comment by oxan** [comment]
Closing due to lack of response.
